Assignment 4 Code review
andreeaiulia13/Assignment4 pull request #1
Opened 2021-05-10 11:48 UTC by andreeaiulia13

2021-05-11 09:03 UTC, VictorMotogna commented on app/helpers/sessions_helper.rb
> +module SessionsHelper
the tabs/spacing in this file seems a little off

2021-05-11 10:44 UTC, VictorMotogna approved these changes

2021-05-11 13:45 UTC, vaneaclaudia requested changes

2021-05-11 13:45 UTC, vaneaclaudia commented on app/controllers/sessions_controller.rb
> +    if(user && user.authenticate(params[:session][:password]))
You don't need parenthesis near `if` clause. 

Also, you can use here the safe navigation operator &. and it would be something like:

`if user&.authenticate(params[:session][:password])` - this means that if user is nil than this line of code will not break, it will be evaluated to nil

2021-05-11 13:45 UTC, vaneaclaudia commented on app/controllers/users_controller.rb
> +      log_in @user
try to be consistent if the way you are calling the methods, either with parenthesis, either without parenthesis, currently I noticed both ways in your code.

2021-05-11 13:45 UTC, vaneaclaudia commented on app/helpers/sessions_helper.rb
> +    !current_user.nil?
I would use `current_user.present?` instead of using negation, it is much more readable.

2021-05-11 13:45 UTC, vaneaclaudia commented on test/models/user_test.rb
> +  test "email should be present" do
Please update the file to use single quotes. You don't need double quotes unless you have string interpolation

2021-05-12 06:12 UTC, vaneaclaudia approved these changes

2021-05-12 06:14 UTC, merged