Assignment5 Code Review
andreeaiulia13/Assignment4 pull request #2
Opened 2021-05-14 14:04 UTC by andreeaiulia13

This is a website for a Food Ordering System

Main changes are:
• implement a more advanced login
• upload images to Cloudinary
• implement add to cart functionality
• write tests to validate that an unauthorezed user can't add a product to the cart

The website can be seen on this Heroku link: https://food-ordering-system-ror.herokuapp.com/

2021-05-17 06:35 UTC, Sunzi2598 commented on app/assets/stylesheets/add_items.scss
> +// Place all the styles related to the AddItems controller here.
Delete this file if it is empty

2021-05-17 06:35 UTC, Sunzi2598 commented on app/assets/stylesheets/carts.scss
> +}
Let a empty line here please

2021-05-17 06:35 UTC, Sunzi2598 commented on app/assets/stylesheets/carts.scss
> +}
same here

2021-05-17 06:35 UTC, Sunzi2598 commented on app/helpers/sessions_helper.rb
> +	end
put end under def

2021-05-17 06:35 UTC, Sunzi2598 commented on app/helpers/sessions_helper.rb
> +	end
same here

2021-05-17 06:35 UTC, Sunzi2598 commented on app/models/user.rb
> +
organize the code here like

attr_accessor :remember_token 

before_save { self.email = email.downcase }

VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

validates :name, presence: true, length: { maximum: 50 }
validates :email, presence: true, length: { maximum: 255 },
 	                  format: { with: VALID_EMAIL_REGEX },
 			  uniqueness: true
validates :password, presence: true, length: { minimum: 6 } 

has_secure_password

2021-05-17 06:35 UTC, Sunzi2598 commented on app/models/user.rb
> +	def forget
identation is not ok here

2021-05-17 06:35 UTC, Sunzi2598 commented on config/cloudinary.yml
> +  static_file_support: false
add an empty line after

2021-05-17 06:35 UTC, Sunzi2598 commented on config/cloudinary.yml
> +  static_file_support: true
same here

2021-05-17 06:35 UTC, Sunzi2598 commented on config/storage.yml
>  # Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
Delete comments

2021-05-17 06:35 UTC, Sunzi2598 commented on db/schema.rb
>  #
same here

2021-05-17 06:35 UTC, Sunzi2598 commented on test/fixtures/add_items.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
same here

2021-05-17 06:35 UTC, Sunzi2598 commented on test/fixtures/carts.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
same here

2021-05-17 06:56 UTC, cristichirtos commented on app/assets/stylesheets/application.css
> +
Add a blank line at the end of the file.

2021-05-17 06:58 UTC, cristichirtos commented on app/controllers/add_items_controller.rb
> +
No need for this empty line here.

2021-05-17 07:03 UTC, cristichirtos commented on app/controllers/application_controller.rb
> +      cart = Cart.find_by(:id => session[:cart_id])
You can just do Cart.find(session[:cart_id]), or Cart.find_by(id: session[:cart_id]) if you want to use the find_by method.

2021-05-17 07:04 UTC, cristichirtos commented on app/controllers/application_controller.rb
> +  before_action :current_cart
If you put this filter in the ApplicationController, it will get invoked on every controller call in your application (even on the login or register actions). Is that the behaviour you wanted?

2021-05-17 07:04 UTC, cristichirtos commented on app/controllers/add_items_controller.rb
> +    current_cart = @current_cart
You can just use @current_cart directly.

2021-05-17 07:06 UTC, cristichirtos commented on app/controllers/add_items_controller.rb
> +	end
Check the indentation for this end.

2021-05-17 07:08 UTC, cristichirtos commented on app/controllers/carts_controller.rb
> +      @cart = @current_cart
You can just use the @current_cart object.

2021-05-17 07:09 UTC, cristichirtos commented on app/controllers/carts_controller.rb
> +    @cart = @current_cart
Same as above.

2021-05-17 07:12 UTC, cristichirtos commented on app/helpers/sessions_helper.rb
> +		elsif (user_id = cookies.encrypted[:user_id])
Check the indentation on lines 17-24.

2021-05-17 07:17 UTC, cristichirtos commented on app/models/cart.rb
> +	end
Check indentation here.

2021-05-17 07:18 UTC, cristichirtos commented on config/cloudinary.yml
> +  cloud_name: dhbjow57v
Don't push private credentials to git. Use dotenv to hide these credentials.

2021-05-17 07:20 UTC, cristichirtos commented on config/routes.rb
> +  get 'carts/:id' => "carts#show", as: "cart"
You can write resources :carts to have these routes defined. You can specify only: [:show, :destroy] if you only want those two.

2021-05-17 07:22 UTC, cristichirtos commented on config/routes.rb
> +  post 'add_items/:id/reduce' => "add_items#reduce_quantity", as: "add_item_reduce"
Sine you have AddItem in your DB, you should update it with a patch request on the same path.
You can use resources :add_items and it will create that patch path along with the others that you need.

2021-05-17 07:24 UTC, cristichirtos commented on db/migrate/20210513115603_create_add_items.rb
> +      t.integer :cart_id
You can have this attribute as a reference to the carts table as a t.references :cart. Same for product.

2021-05-17 07:31 UTC, cristichirtos reviewed
Congrats on your work! Be careful with the indentation and try to clarify a bit your add to cart implementation. Other than that, nice work!

2021-05-17 10:46 UTC, cristichirtos approved these changes

2021-05-17 10:51 UTC, Sunzi2598 approved these changes
Good Job, Andreea! 👍

2021-05-18 06:26 UTC, VictorMotogna commented on app/controllers/add_items_controller.rb
> +      @add_item = @current_cart.add_items.find_by(:product_id => chosen_product)
you should use the new ruby hash syntax here:
```ruby
cart.find_by(product_id: chosen_product)
```

2021-05-18 06:26 UTC, VictorMotogna commented on app/controllers/application_controller.rb
> +    if session[:cart_id]
you could refactor this into:
```ruby
if session[:cart_id].present?
  cart = ..
else
  @current_cart = ..
end
```

2021-05-18 06:26 UTC, VictorMotogna commented on app/helpers/sessions_helper.rb
> +    if (user_id = session[:user_id])
If I'm correct, you have here:
```ruby
if
elsif
if
end
```

You should either continue using `elsif` or put and `end`

2021-05-18 06:26 UTC, VictorMotogna commented on app/views/products/index.html.haml
> +
I think you need a newline at the end of this file

2021-05-18 06:26 UTC, VictorMotogna commented on config/cloudinary.yml
> +test:
I think that you can remove this, if you don't change the `active_storage.service` in the `environments/test.rb`, and the test environment should use the local storage and not upload to Cloudinary

2021-05-18 06:26 UTC, VictorMotogna commented on config/routes.rb
> +  resources :add_items
here you could do:
```ruby
resources :add_items do
  patch :add, on: :member
  patch :reduce, on: :member
end
```

2021-05-18 06:26 UTC, VictorMotogna commented on db/migrate/20210513115603_create_add_items.rb
> +      t.integer :quantity
I think that you could add here `, default: 1` and change `AddItem.create(quantity: 1)` to `AddItem.create`

2021-05-18 06:26 UTC, VictorMotogna commented on spec/requests/carts_spec.rb
> +        expect(response).to redirect_to login_path
I usually like adding a newline between the logic that creates items, calls an endpoint, etc.. and the `expect`. It makes it easier to read

2021-05-18 06:26 UTC, VictorMotogna commented on test/controllers/carts_controller_test.rb
> +    assert_response :success
You have some files using RSpec and some using integration tests

2021-05-18 07:43 UTC, andreeaiulia13 commented on test/controllers/carts_controller_test.rb
> +    assert_response :success
I used the integration tests from the book, to test my code. Should I convert them in RSpec tests or can I delete them since they are not even optional for our assignment?

2021-05-18 13:03 UTC, VictorMotogna commented on app/views/carts/show.html.haml
> +
I think you need a newline at the end of this file

2021-05-18 15:46 UTC, AdrianFlorian requested changes
Good job Andreea, just a few comments from my end 👍

2021-05-18 15:46 UTC, AdrianFlorian commented on app/controllers/add_items_controller.rb
> +
no need for empty line here :-)

2021-05-18 15:46 UTC, AdrianFlorian commented on app/controllers/add_items_controller.rb
> +      @add_item = AddItem.new
Is `AddItem` a good name? 'add item' signifies an action -> 'add an item', the name of a class should be a subject - like CartItem, or just Item. Does it make sense?

2021-05-18 15:46 UTC, AdrianFlorian commented on app/controllers/application_controller.rb
> +
no need for this empty line here :-)

2021-05-18 15:46 UTC, AdrianFlorian commented on app/models/cart.rb
> +    self.add_items.each do |item|
A nicer to read version `self.add_items.map(&:total_price).sum`

2021-05-18 15:46 UTC, AdrianFlorian commented on app/views/products/dashboard.html.haml
> +          %td= product.price.to_s + ' $'
Please use the ruby preferred way `"#{product.price} $"`

2021-05-20 06:53 UTC, merged

2021-05-20 06:53 UTC, VictorMotogna approved these changes