Assignment6 Code Review
andreeaiulia13/Assignment4 pull request #3
Opened 2021-05-20 14:55 UTC by andreeaiulia13

This is a website for a Food Ordering System

Main changes are:

- Add user activation via email
- Add reset password option
- Write tests to make sure that a user that is not activated cannot access the site
The website can be visualized  [https://food-ordering-system-ror.herokuapp.com/](here:)

2021-05-21 09:14 UTC, sasaranAndrei reviewed
Nice work, Andreea!

2021-05-21 09:14 UTC, sasaranAndrei commented on config/routes.rb
> +  resources :password_resets, only: [:new, :create, :edit, :update]
You can use `only: %i[new create edit update]` since there's a list of symbols.

2021-05-21 09:14 UTC, sasaranAndrei commented on config/routes.rb
> +  get 'password_resets/edit'
Also, you can remove these lines since you used `resources :password_resets, only: [:new, :create, :edit, :update]`.

2021-05-21 09:14 UTC, sasaranAndrei commented on app/controllers/password_resets_controller.rb
> +      redirect_to root_url
You could refactor this into a one liner. Also, I think you can remove the parentheses like this: 
``unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])``

2021-05-21 09:14 UTC, sasaranAndrei commented on app/views/user_mailer/password_reset.text.haml
> +If you did not request your password to be reset, please ignore this email and your password will stay as it is.
It looks like there's no newline at the end of this file. Maybe you missed it.

2021-05-21 09:44 UTC, flaviuvr requested changes
Great job, here are my comments on how you could improve the code🙌

2021-05-21 09:44 UTC, flaviuvr commented on app/assets/stylesheets/sessions.scss
> +}
Using scss a nicer way to do this is by nesting the two of them, like so:

`.forgot-password {  
  color: green;

  &:hover {
    color: #b95814
    }
}`

2021-05-21 09:44 UTC, flaviuvr commented on app/controllers/password_resets_controller.rb
> +      redirect_to new_password_reset_url
You could use a guard clause here for cleaner code, replacing the if with:
`return unless @user.password_reset_expired?`

2021-05-21 09:44 UTC, flaviuvr commented on config/routes.rb
> +  resources :account_activations, only: [:edit]
You can remove the brackets here, as there is only one method

2021-05-21 09:44 UTC, flaviuvr commented on spec/requests/account_activations_spec.rb
> +      let(:user) { User.create(name: 'Andreea', email: 'andreeaiulia@gmail.com', password: '123456', password_confirmation: '123456')}
To avoid code repetition you could define this variable outside both contexts, right after describe

2021-05-21 09:44 UTC, flaviuvr commented on spec/requests/account_activations_spec.rb
> +        post login_path, params: {session: { email: user.email, password: user.password }}
Also you could make this a subject outside the contexts and call it on the first line of every test

2021-05-21 11:26 UTC, andreeaiulia13 commented on spec/requests/account_activations_spec.rb
> +      let(:user) { User.create(name: 'Andreea', email: 'andreeaiulia@gmail.com', password: '123456', password_confirmation: '123456')}
@flaviuvr If I'm defining the user variable from the second test outside the context, the test is not seeing it anymore

2021-05-21 12:37 UTC, flaviuvr reviewed
As a side note, what would help in the future would be naming the branches and PRs to be a bit more specific. For the branch names, you could take inspiration from the ones used in the book. They should describe the feature that you are working on. Same for the PR names.

2021-05-21 12:38 UTC, flaviuvr approved these changes
Well done👌

2021-05-21 13:53 UTC, sasaranAndrei approved these changes
Good job, Andreea! Don't forget to 'Resolve conversations' that are outdated.

2021-05-24 07:02 UTC, VictorMotogna commented on app/controllers/account_activations_controller.rb
> +    if user && !user.activated? && user.authenticated?(:activation, params[:id])
I think you could simplify this `if` condition using `unless` and `user&` (`user&.authenticated?`, `user&.activated?`)

2021-05-24 07:02 UTC, VictorMotogna commented on app/controllers/password_resets_controller.rb
> +   redirect_to root_url unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
same here, the condition could be simplified

2021-05-24 07:02 UTC, VictorMotogna commented on app/helpers/sessions_helper.rb
> +      if user && user.authenticated?(:remember, cookies[:remember_token])
you could simplify this to `user&.authenticated?`

2021-05-24 07:02 UTC, VictorMotogna commented on app/models/user.rb
> +    BCrypt::Password.new(digest).is_password?(token)
you should add a newline after a `return`

2021-05-24 07:02 UTC, VictorMotogna commented on config/environments/production.rb
> +  ActionMailer::Base.smtp_settings = {
I think you could use the new ruby hash syntax here:
```ruby
{
  port: ENV['MAILGUN_PORT'],
  address: ENV['MAILGUN_ADDRESS'],
  etc.
}
```

2021-05-24 08:01 UTC, andreeaiulia13 commented on app/controllers/account_activations_controller.rb
> +    if user && !user.activated? && user.authenticated?(:activation, params[:id])
@VictorMotogna 
unless user&(user.activated?, user.authenticated?(:activation, params[:id]))
I have an error if I write the condition like this. What is the correct way of writing it?

2021-05-24 08:04 UTC, andreeaiulia13 commented on app/controllers/account_activations_controller.rb
> +    if user && !user.activated? && user.authenticated?(:activation, params[:id])
unless user&.activated? && user&.authenticated?(:activation, params[:id])

2021-05-24 08:05 UTC, andreeaiulia13 commented on app/controllers/account_activations_controller.rb
> +    if user && !user.activated? && user.authenticated?(:activation, params[:id])
Is it simplified enough?

2021-05-25 06:53 UTC, VictorMotogna commented on app/controllers/account_activations_controller.rb
> +    unless user&.activated? && user.authenticated?(:activation, params[:id])
When changing to unless you'll also have to change `&&` with `||`. For example:

```ruby
if true && false
  # does not get here
end

unless true && false
  # does get here
end

unless true || false
  # does not get here
end
```

If you want to debug, you could add a debug point and see the output of your condition when using if and when using unless

2021-05-25 07:00 UTC, andreeaiulia13 commented on app/controllers/account_activations_controller.rb
> +    unless user&.activated? && user.authenticated?(:activation, params[:id])
But I've also changed the negation of user.activated. I've tried with || but it is entering the else condition.

2021-05-25 07:18 UTC, vaneaclaudia requested changes

2021-05-25 07:18 UTC, vaneaclaudia commented on app/controllers/account_activations_controller.rb
> +      user.update_attribute(:activated_at, Time.zone.now)
you could use `update` method here and have a single transaction

2021-05-25 07:18 UTC, vaneaclaudia commented on app/models/user.rb
> +    update_attribute(:reset_sent_at, Time.zone.now)
same remark here regarding update

2021-05-25 07:18 UTC, vaneaclaudia commented on spec/requests/account_activations_spec.rb
> +RSpec.describe 'Account Activations', type: :request do
Rspec.describe should describe the class you are testing so should have the class name

2021-05-25 07:18 UTC, vaneaclaudia commented on spec/requests/account_activations_spec.rb
> +    subject {post login_path, params: {session: { email: user.email, password: user.password }}}
leave an empty space inside the {}

2021-05-25 07:18 UTC, vaneaclaudia commented on spec/requests/account_activations_spec.rb
> +      let(:user) { User.create(name: 'Example', email: 'example1@gmail.com', password: '123456', password_confirmation: '123456')}
use factory bot for creating records in tests

2021-05-25 13:10 UTC, VictorMotogna commented on app/controllers/account_activations_controller.rb
> +    unless user&.activated? && user.authenticated?(:activation, params[:id])
In that case it's ok 👍

2021-05-26 06:37 UTC, AdrianFlorian commented
@andreeaiulia13 can we have a test user please?

2021-05-26 06:40 UTC, AdrianFlorian requested changes
@andreeaiulia13 just a small change, nice job!

2021-05-26 06:40 UTC, AdrianFlorian commented on app/models/user.rb
> +  def create_reset_digest
add a `!` (called 'bang') at the end of the method name. `!` signalize that this method changes the internal state of the object.

2021-05-26 06:40 UTC, AdrianFlorian commented on app/models/user.rb
> +    self.email = email.downcase
here for example, it's ok :-)

but if you would also do `self.save!` you should have a `!` on `downcase_email` as well.

2021-05-26 09:49 UTC, VictorMotogna commented on Gemfile
> +gem 'database_cleaner',           '~> 2.0', '>= 2.0.1'
I think database_cleaner can also be added to the development/test group

2021-05-26 09:49 UTC, VictorMotogna commented on app/controllers/account_activations_controller.rb
> +    unless user&.activated? && user.authenticated?(:activation, params[:id])
I think you'll need to add a safe operator to the second check too. If the user is nil, the first check will return false and the second will say `no method authenticated? for nil`

2021-05-26 09:49 UTC, VictorMotogna commented on app/controllers/password_resets_controller.rb
> +   redirect_to root_url unless @user&.activated? && @user.authenticated?(:reset, params[:id])
Same here, add safe operator to second check too

2021-05-26 09:49 UTC, VictorMotogna commented on spec/requests/account_activations_spec.rb
> +      let(:user) { create :user }
I would move these `let(:user)` and `let(:activated_user)` to the top of the file, above `describe`

2021-05-26 09:49 UTC, VictorMotogna commented on spec/factories.rb
> +    name  { 'Example' }
If you want (not required), you could also look into [Faker](https://github.com/faker-ruby/faker) for mocking fields

2021-05-26 09:49 UTC, VictorMotogna commented on spec/support/factory_bot.rb
> +RSpec.configure do |config|
You should add a newline between requires and rest

2021-05-26 11:40 UTC, VictorMotogna approved these changes
Nice job!

2021-05-26 11:40 UTC, VictorMotogna commented on spec/factories.rb
> +FactoryBot.define do
nice!!

2021-05-27 09:58 UTC, vaneaclaudia approved these changes

2021-05-27 09:59 UTC, merged